### ISSUE TITLE
package name in project.janet, github repo name

### ISSUE THREAD

**Issue by uvtc** [janet-lang/pkgs#18]
In the contributing file, in the bullet list at the top, would it make sense for it to have one more bullet point specifying that the project name in the project's project.janet file should match the name of the github repo? (Maybe this is already implied, but not made explicit?)

**Comment by pepe** [comment]
Yes, that is a good rule. But there are already many projects which do not have it this way. For example, https://github.com/andrewchambers/janet-big got big as project.janet `:name` and it is under `'bigint` in the pkg.

Now I need to think about what could be done here. Maybe we will really need a retrospective before the second phase.

Thank you.

**Comment by pepe** [comment]
So with the new rules in the CONTRIBUTING, I would say we can close this issue. Please feel free to open a new issue if you are not satisfied. I found your insights valuable on every occasion. Frankly, I consider our contest on markdown docs better be won by you after all. 

When the repository stabilizes, I will do a retrospective on pkgs already in and develop a fixing process.

Thank you!

**Comment by uvtc** [comment]
You're welcome, Pepe, and thanks for your work here and elsewhere!
