### ISSUE TITLE
jurl and jurl@bakpakin

### ISSUE THREAD

**Issue by uvtc** [janet-lang/pkgs#43]
@bakpakin ,  pkgs.janet lists both [jurl](https://github.com/sepisoad/jurl) and [jurl@bakpakin](https://github.com/bakpakin/jurl), though I notice that jurl is 15 commits ahead of jurl@bakpakin. Is jurl@bakpakin still actively developed and would you like it to remain in pkgs.janet ?

**Comment by pepe** [comment]
Ping @bakpakin?

**Comment by bakpakin** [comment]
Nah, we should drop it. Part of the reason was to introduce a standard way to maintain multiple forks of the same package. But the package itself largely isn't needed.
