### ISSUE TITLE
name conflict

### ISSUE THREAD

**Issue by CosmicToast** [janet-lang/pkgs#56]
Hi!

I wrote a fairly complete (~95+% I haven't measured exactly, but you can count the things I haven't implemented on your fingers) curl_easy wrapper.
I named it [jurl](https://github.com/cosmictoast/jurl.git) because it was the obvious name to use.

Now, however, I realize that there is [another such package](https://github.com/sepisoad/jurl.git) already registered here.

Notably, my package is now ready for production use (it's actually currently being used in a production testing environment, soon to be in full production), and significantly more complete and up to date than the other one.

What is the preferred approach towards name conflict resolution?

**Comment by bakpakin** [comment]
So just in case you hadn't realized, you can use packages by raw URL as well as the short names. That said, open a PR and we will take a look. The old binding was quite incomplete so we may merge it and update the official listing.
